%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'Modelo';
M_.dynare_version = '4.5.7';
oo_.dynare_version = '4.5.7';
options_.dynare_version = '4.5.7';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('Modelo.log');
M_.exo_names = 'e1';
M_.exo_names_tex = 'e1';
M_.exo_names_long = 'e1';
M_.exo_names = char(M_.exo_names, 'e2');
M_.exo_names_tex = char(M_.exo_names_tex, 'e2');
M_.exo_names_long = char(M_.exo_names_long, 'e2');
M_.exo_names = char(M_.exo_names, 'e3');
M_.exo_names_tex = char(M_.exo_names_tex, 'e3');
M_.exo_names_long = char(M_.exo_names_long, 'e3');
M_.exo_names = char(M_.exo_names, 'e4');
M_.exo_names_tex = char(M_.exo_names_tex, 'e4');
M_.exo_names_long = char(M_.exo_names_long, 'e4');
M_.exo_names = char(M_.exo_names, 'e5');
M_.exo_names_tex = char(M_.exo_names_tex, 'e5');
M_.exo_names_long = char(M_.exo_names_long, 'e5');
M_.exo_names = char(M_.exo_names, 'e6');
M_.exo_names_tex = char(M_.exo_names_tex, 'e6');
M_.exo_names_long = char(M_.exo_names_long, 'e6');
M_.exo_names = char(M_.exo_names, 'e7');
M_.exo_names_tex = char(M_.exo_names_tex, 'e7');
M_.exo_names_long = char(M_.exo_names_long, 'e7');
M_.exo_names = char(M_.exo_names, 'e8');
M_.exo_names_tex = char(M_.exo_names_tex, 'e8');
M_.exo_names_long = char(M_.exo_names_long, 'e8');
M_.exo_names = char(M_.exo_names, 'e9');
M_.exo_names_tex = char(M_.exo_names_tex, 'e9');
M_.exo_names_long = char(M_.exo_names_long, 'e9');
M_.exo_names = char(M_.exo_names, 'e10');
M_.exo_names_tex = char(M_.exo_names_tex, 'e10');
M_.exo_names_long = char(M_.exo_names_long, 'e10');
M_.exo_names = char(M_.exo_names, 'e11');
M_.exo_names_tex = char(M_.exo_names_tex, 'e11');
M_.exo_names_long = char(M_.exo_names_long, 'e11');
M_.exo_names = char(M_.exo_names, 'e12');
M_.exo_names_tex = char(M_.exo_names_tex, 'e12');
M_.exo_names_long = char(M_.exo_names_long, 'e12');
M_.exo_names = char(M_.exo_names, 'e13');
M_.exo_names_tex = char(M_.exo_names_tex, 'e13');
M_.exo_names_long = char(M_.exo_names_long, 'e13');
M_.exo_names = char(M_.exo_names, 'e14');
M_.exo_names_tex = char(M_.exo_names_tex, 'e14');
M_.exo_names_long = char(M_.exo_names_long, 'e14');
M_.exo_names = char(M_.exo_names, 'e15');
M_.exo_names_tex = char(M_.exo_names_tex, 'e15');
M_.exo_names_long = char(M_.exo_names_long, 'e15');
M_.exo_names = char(M_.exo_names, 'e16');
M_.exo_names_tex = char(M_.exo_names_tex, 'e16');
M_.exo_names_long = char(M_.exo_names_long, 'e16');
M_.exo_names = char(M_.exo_names, 'e17');
M_.exo_names_tex = char(M_.exo_names_tex, 'e17');
M_.exo_names_long = char(M_.exo_names_long, 'e17');
M_.exo_names = char(M_.exo_names, 'e18');
M_.exo_names_tex = char(M_.exo_names_tex, 'e18');
M_.exo_names_long = char(M_.exo_names_long, 'e18');
M_.exo_names = char(M_.exo_names, 'e19');
M_.exo_names_tex = char(M_.exo_names_tex, 'e19');
M_.exo_names_long = char(M_.exo_names_long, 'e19');
M_.exo_names = char(M_.exo_names, 'e20');
M_.exo_names_tex = char(M_.exo_names_tex, 'e20');
M_.exo_names_long = char(M_.exo_names_long, 'e20');
M_.exo_names = char(M_.exo_names, 'e21');
M_.exo_names_tex = char(M_.exo_names_tex, 'e21');
M_.exo_names_long = char(M_.exo_names_long, 'e21');
M_.exo_names = char(M_.exo_names, 'e22');
M_.exo_names_tex = char(M_.exo_names_tex, 'e22');
M_.exo_names_long = char(M_.exo_names_long, 'e22');
M_.exo_names = char(M_.exo_names, 'e23');
M_.exo_names_tex = char(M_.exo_names_tex, 'e23');
M_.exo_names_long = char(M_.exo_names_long, 'e23');
M_.exo_names = char(M_.exo_names, 'e24');
M_.exo_names_tex = char(M_.exo_names_tex, 'e24');
M_.exo_names_long = char(M_.exo_names_long, 'e24');
M_.exo_names = char(M_.exo_names, 'e25');
M_.exo_names_tex = char(M_.exo_names_tex, 'e25');
M_.exo_names_long = char(M_.exo_names_long, 'e25');
M_.exo_names = char(M_.exo_names, 'e26');
M_.exo_names_tex = char(M_.exo_names_tex, 'e26');
M_.exo_names_long = char(M_.exo_names_long, 'e26');
M_.endo_names = 'c';
M_.endo_names_tex = 'c';
M_.endo_names_long = 'c';
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, 'n');
M_.endo_names_long = char(M_.endo_names_long, 'n');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'ir');
M_.endo_names_tex = char(M_.endo_names_tex, 'ir');
M_.endo_names_long = char(M_.endo_names_long, 'ir');
M_.endo_names = char(M_.endo_names, 'bf');
M_.endo_names_tex = char(M_.endo_names_tex, 'bf');
M_.endo_names_long = char(M_.endo_names_long, 'bf');
M_.endo_names = char(M_.endo_names, 'er');
M_.endo_names_tex = char(M_.endo_names_tex, 'er');
M_.endo_names_long = char(M_.endo_names_long, 'er');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, 'q');
M_.endo_names_long = char(M_.endo_names_long, 'q');
M_.endo_names = char(M_.endo_names, 'i');
M_.endo_names_tex = char(M_.endo_names_tex, 'i');
M_.endo_names_long = char(M_.endo_names_long, 'i');
M_.endo_names = char(M_.endo_names, 'ifdi');
M_.endo_names_tex = char(M_.endo_names_tex, 'ifdi');
M_.endo_names_long = char(M_.endo_names_long, 'ifdi');
M_.endo_names = char(M_.endo_names, 'k');
M_.endo_names_tex = char(M_.endo_names_tex, 'k');
M_.endo_names_long = char(M_.endo_names_long, 'k');
M_.endo_names = char(M_.endo_names, 'kfdi');
M_.endo_names_tex = char(M_.endo_names_tex, 'kfdi');
M_.endo_names_long = char(M_.endo_names_long, 'kfdi');
M_.endo_names = char(M_.endo_names, 'kv');
M_.endo_names_tex = char(M_.endo_names_tex, 'kv');
M_.endo_names_long = char(M_.endo_names_long, 'kv');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'rfdi');
M_.endo_names_tex = char(M_.endo_names_tex, 'rfdi');
M_.endo_names_long = char(M_.endo_names_long, 'rfdi');
M_.endo_names = char(M_.endo_names, 'fi');
M_.endo_names_tex = char(M_.endo_names_tex, 'fi');
M_.endo_names_long = char(M_.endo_names_long, 'fi');
M_.endo_names = char(M_.endo_names, 'df');
M_.endo_names_tex = char(M_.endo_names_tex, 'df');
M_.endo_names_long = char(M_.endo_names_long, 'df');
M_.endo_names = char(M_.endo_names, 'py');
M_.endo_names_tex = char(M_.endo_names_tex, 'py');
M_.endo_names_long = char(M_.endo_names_long, 'py');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'y');
M_.endo_names = char(M_.endo_names, 'g');
M_.endo_names_tex = char(M_.endo_names_tex, 'g');
M_.endo_names_long = char(M_.endo_names_long, 'g');
M_.endo_names = char(M_.endo_names, 'd');
M_.endo_names_tex = char(M_.endo_names_tex, 'd');
M_.endo_names_long = char(M_.endo_names_long, 'd');
M_.endo_names = char(M_.endo_names, 'm');
M_.endo_names_tex = char(M_.endo_names_tex, 'm');
M_.endo_names_long = char(M_.endo_names_long, 'm');
M_.endo_names = char(M_.endo_names, 's');
M_.endo_names_tex = char(M_.endo_names_tex, 's');
M_.endo_names_long = char(M_.endo_names_long, 's');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, 'x');
M_.endo_names_long = char(M_.endo_names_long, 'x');
M_.endo_names = char(M_.endo_names, 'pm');
M_.endo_names_tex = char(M_.endo_names_tex, 'pm');
M_.endo_names_long = char(M_.endo_names_long, 'pm');
M_.endo_names = char(M_.endo_names, 'pd');
M_.endo_names_tex = char(M_.endo_names_tex, 'pd');
M_.endo_names_long = char(M_.endo_names_long, 'pd');
M_.endo_names = char(M_.endo_names, 'px');
M_.endo_names_tex = char(M_.endo_names_tex, 'px');
M_.endo_names_long = char(M_.endo_names_long, 'px');
M_.endo_names = char(M_.endo_names, 'xx');
M_.endo_names_tex = char(M_.endo_names_tex, 'xx');
M_.endo_names_long = char(M_.endo_names_long, 'xx');
M_.endo_names = char(M_.endo_names, 'xt');
M_.endo_names_tex = char(M_.endo_names_tex, 'xt');
M_.endo_names_long = char(M_.endo_names_long, 'xt');
M_.endo_names = char(M_.endo_names, 'pwx');
M_.endo_names_tex = char(M_.endo_names_tex, 'pwx');
M_.endo_names_long = char(M_.endo_names_long, 'pwx');
M_.endo_names = char(M_.endo_names, 'pib');
M_.endo_names_tex = char(M_.endo_names_tex, 'pib');
M_.endo_names_long = char(M_.endo_names_long, 'pib');
M_.endo_names = char(M_.endo_names, 'ri');
M_.endo_names_tex = char(M_.endo_names_tex, 'ri');
M_.endo_names_long = char(M_.endo_names_long, 'ri');
M_.endo_names = char(M_.endo_names, 'tauh');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauh');
M_.endo_names_long = char(M_.endo_names_long, 'tauh');
M_.endo_names = char(M_.endo_names, 'tauk');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauk');
M_.endo_names_long = char(M_.endo_names_long, 'tauk');
M_.endo_names = char(M_.endo_names, 'f');
M_.endo_names_tex = char(M_.endo_names_tex, 'f');
M_.endo_names_long = char(M_.endo_names_long, 'f');
M_.endo_names = char(M_.endo_names, 'fk');
M_.endo_names_tex = char(M_.endo_names_tex, 'fk');
M_.endo_names_long = char(M_.endo_names_long, 'fk');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'z');
M_.endo_names = char(M_.endo_names, 'iva');
M_.endo_names_tex = char(M_.endo_names_tex, 'iva');
M_.endo_names_long = char(M_.endo_names_long, 'iva');
M_.endo_names = char(M_.endo_names, 'aran');
M_.endo_names_tex = char(M_.endo_names_tex, 'aran');
M_.endo_names_long = char(M_.endo_names_long, 'aran');
M_.endo_names = char(M_.endo_names, 'dm');
M_.endo_names_tex = char(M_.endo_names_tex, 'dm');
M_.endo_names_long = char(M_.endo_names_long, 'dm');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'vr');
M_.endo_names_tex = char(M_.endo_names_tex, 'vr');
M_.endo_names_long = char(M_.endo_names_long, 'vr');
M_.endo_names = char(M_.endo_names, 'ppet');
M_.endo_names_tex = char(M_.endo_names_tex, 'ppet');
M_.endo_names_long = char(M_.endo_names_long, 'ppet');
M_.endo_names = char(M_.endo_names, 'qpet');
M_.endo_names_tex = char(M_.endo_names_tex, 'qpet');
M_.endo_names_long = char(M_.endo_names_long, 'qpet');
M_.endo_names = char(M_.endo_names, 'lamda');
M_.endo_names_tex = char(M_.endo_names_tex, 'lamda');
M_.endo_names_long = char(M_.endo_names_long, 'lamda');
M_.endo_names = char(M_.endo_names, 'ga');
M_.endo_names_tex = char(M_.endo_names_tex, 'ga');
M_.endo_names_long = char(M_.endo_names_long, 'ga');
M_.endo_names = char(M_.endo_names, 'po');
M_.endo_names_tex = char(M_.endo_names_tex, 'po');
M_.endo_names_long = char(M_.endo_names_long, 'po');
M_.endo_names = char(M_.endo_names, 'v1');
M_.endo_names_tex = char(M_.endo_names_tex, 'v1');
M_.endo_names_long = char(M_.endo_names_long, 'v1');
M_.endo_names = char(M_.endo_names, 'v2');
M_.endo_names_tex = char(M_.endo_names_tex, 'v2');
M_.endo_names_long = char(M_.endo_names_long, 'v2');
M_.endo_names = char(M_.endo_names, 'iri');
M_.endo_names_tex = char(M_.endo_names_tex, 'iri');
M_.endo_names_long = char(M_.endo_names_long, 'iri');
M_.endo_names = char(M_.endo_names, 'gb');
M_.endo_names_tex = char(M_.endo_names_tex, 'gb');
M_.endo_names_long = char(M_.endo_names_long, 'gb');
M_.endo_names = char(M_.endo_names, 'rb');
M_.endo_names_tex = char(M_.endo_names_tex, 'rb');
M_.endo_names_long = char(M_.endo_names_long, 'rb');
M_.endo_names = char(M_.endo_names, 'irb');
M_.endo_names_tex = char(M_.endo_names_tex, 'irb');
M_.endo_names_long = char(M_.endo_names_long, 'irb');
M_.endo_names = char(M_.endo_names, 'tc');
M_.endo_names_tex = char(M_.endo_names_tex, 'tc');
M_.endo_names_long = char(M_.endo_names_long, 'tc');
M_.endo_names = char(M_.endo_names, 'cb');
M_.endo_names_tex = char(M_.endo_names_tex, 'cb');
M_.endo_names_long = char(M_.endo_names_long, 'cb');
M_.endo_names = char(M_.endo_names, 'ira');
M_.endo_names_tex = char(M_.endo_names_tex, 'ira');
M_.endo_names_long = char(M_.endo_names_long, 'ira');
M_.endo_names = char(M_.endo_names, 'walras');
M_.endo_names_tex = char(M_.endo_names_tex, 'walras');
M_.endo_names_long = char(M_.endo_names_long, 'walras');
M_.endo_names = char(M_.endo_names, 'scc');
M_.endo_names_tex = char(M_.endo_names_tex, 'scc');
M_.endo_names_long = char(M_.endo_names_long, 'scc');
M_.endo_names = char(M_.endo_names, 'sck');
M_.endo_names_tex = char(M_.endo_names_tex, 'sck');
M_.endo_names_long = char(M_.endo_names_long, 'sck');
M_.endo_names = char(M_.endo_names, 'pw');
M_.endo_names_tex = char(M_.endo_names_tex, 'pw');
M_.endo_names_long = char(M_.endo_names_long, 'pw');
M_.endo_names = char(M_.endo_names, 'iv');
M_.endo_names_tex = char(M_.endo_names_tex, 'iv');
M_.endo_names_long = char(M_.endo_names_long, 'iv');
M_.endo_names = char(M_.endo_names, 'rv');
M_.endo_names_tex = char(M_.endo_names_tex, 'rv');
M_.endo_names_long = char(M_.endo_names_long, 'rv');
M_.endo_names = char(M_.endo_names, 'pv');
M_.endo_names_tex = char(M_.endo_names_tex, 'pv');
M_.endo_names_long = char(M_.endo_names_long, 'pv');
M_.endo_names = char(M_.endo_names, 'yv');
M_.endo_names_tex = char(M_.endo_names_tex, 'yv');
M_.endo_names_long = char(M_.endo_names_long, 'yv');
M_.endo_names = char(M_.endo_names, 'yt');
M_.endo_names_tex = char(M_.endo_names_tex, 'yt');
M_.endo_names_long = char(M_.endo_names_long, 'yt');
M_.endo_names = char(M_.endo_names, 'pt');
M_.endo_names_tex = char(M_.endo_names_tex, 'pt');
M_.endo_names_long = char(M_.endo_names_long, 'pt');
M_.endo_names = char(M_.endo_names, 'taukv');
M_.endo_names_tex = char(M_.endo_names_tex, 'taukv');
M_.endo_names_long = char(M_.endo_names_long, 'taukv');
M_.endo_names = char(M_.endo_names, 'kapa');
M_.endo_names_tex = char(M_.endo_names_tex, 'kapa');
M_.endo_names_long = char(M_.endo_names_long, 'kapa');
M_.endo_names = char(M_.endo_names, 'ltv');
M_.endo_names_tex = char(M_.endo_names_tex, 'ltv');
M_.endo_names_long = char(M_.endo_names_long, 'ltv');
M_.endo_names = char(M_.endo_names, 'irh');
M_.endo_names_tex = char(M_.endo_names_tex, 'irh');
M_.endo_names_long = char(M_.endo_names_long, 'irh');
M_.endo_names = char(M_.endo_names, 'ch');
M_.endo_names_tex = char(M_.endo_names_tex, 'ch');
M_.endo_names_long = char(M_.endo_names_long, 'ch');
M_.endo_names = char(M_.endo_names, 'tauv');
M_.endo_names_tex = char(M_.endo_names_tex, 'tauv');
M_.endo_names_long = char(M_.endo_names_long, 'tauv');
M_.endo_names = char(M_.endo_names, 'rrb');
M_.endo_names_tex = char(M_.endo_names_tex, 'rrb');
M_.endo_names_long = char(M_.endo_names_long, 'rrb');
M_.endo_names = char(M_.endo_names, 'psiv');
M_.endo_names_tex = char(M_.endo_names_tex, 'psiv');
M_.endo_names_long = char(M_.endo_names_long, 'psiv');
M_.endo_names = char(M_.endo_names, 'psim');
M_.endo_names_tex = char(M_.endo_names_tex, 'psim');
M_.endo_names_long = char(M_.endo_names_long, 'psim');
M_.endo_names = char(M_.endo_names, 'psin');
M_.endo_names_tex = char(M_.endo_names_tex, 'psin');
M_.endo_names_long = char(M_.endo_names_long, 'psin');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, 'u');
M_.endo_names_long = char(M_.endo_names_long, 'u');
M_.endo_names = char(M_.endo_names, 'pomeg');
M_.endo_names_tex = char(M_.endo_names_tex, 'pomeg');
M_.endo_names_long = char(M_.endo_names_long, 'pomeg');
M_.endo_names = char(M_.endo_names, 'omeg');
M_.endo_names_tex = char(M_.endo_names_tex, 'omeg');
M_.endo_names_long = char(M_.endo_names_long, 'omeg');
M_.endo_names = char(M_.endo_names, 'rs');
M_.endo_names_tex = char(M_.endo_names_tex, 'rs');
M_.endo_names_long = char(M_.endo_names_long, 'rs');
M_.endo_names = char(M_.endo_names, 'sdomeg');
M_.endo_names_tex = char(M_.endo_names_tex, 'sdomeg');
M_.endo_names_long = char(M_.endo_names_long, 'sdomeg');
M_.endo_names = char(M_.endo_names, 'chi');
M_.endo_names_tex = char(M_.endo_names_tex, 'chi');
M_.endo_names_long = char(M_.endo_names_long, 'chi');
M_.endo_names = char(M_.endo_names, 'ct');
M_.endo_names_tex = char(M_.endo_names_tex, 'ct');
M_.endo_names_long = char(M_.endo_names_long, 'ct');
M_.endo_partitions = struct();
M_.param_names = 'psin0';
M_.param_names_tex = 'psin0';
M_.param_names_long = 'psin0';
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'tauh0');
M_.param_names_tex = char(M_.param_names_tex, 'tauh0');
M_.param_names_long = char(M_.param_names_long, 'tauh0');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, 'delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'gama');
M_.param_names_tex = char(M_.param_names_tex, 'gama');
M_.param_names_long = char(M_.param_names_long, 'gama');
M_.param_names = char(M_.param_names, 'tauk0');
M_.param_names_tex = char(M_.param_names_tex, 'tauk0');
M_.param_names_long = char(M_.param_names_long, 'tauk0');
M_.param_names = char(M_.param_names, 'f0');
M_.param_names_tex = char(M_.param_names_tex, 'f0');
M_.param_names_long = char(M_.param_names_long, 'f0');
M_.param_names = char(M_.param_names, 'fk0');
M_.param_names_tex = char(M_.param_names_tex, 'fk0');
M_.param_names_long = char(M_.param_names_long, 'fk0');
M_.param_names = char(M_.param_names, 'alfa1');
M_.param_names_tex = char(M_.param_names_tex, 'alfa1');
M_.param_names_long = char(M_.param_names_long, 'alfa1');
M_.param_names = char(M_.param_names, 'alfa2');
M_.param_names_tex = char(M_.param_names_tex, 'alfa2');
M_.param_names_long = char(M_.param_names_long, 'alfa2');
M_.param_names = char(M_.param_names, 'alfa3');
M_.param_names_tex = char(M_.param_names_tex, 'alfa3');
M_.param_names_long = char(M_.param_names_long, 'alfa3');
M_.param_names = char(M_.param_names, 'z0');
M_.param_names_tex = char(M_.param_names_tex, 'z0');
M_.param_names_long = char(M_.param_names_long, 'z0');
M_.param_names = char(M_.param_names, 'b');
M_.param_names_tex = char(M_.param_names_tex, 'b');
M_.param_names_long = char(M_.param_names_long, 'b');
M_.param_names = char(M_.param_names, 'sig');
M_.param_names_tex = char(M_.param_names_tex, 'sig');
M_.param_names_long = char(M_.param_names_long, 'sig');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'iva0');
M_.param_names_tex = char(M_.param_names_tex, 'iva0');
M_.param_names_long = char(M_.param_names_long, 'iva0');
M_.param_names = char(M_.param_names, 'g0');
M_.param_names_tex = char(M_.param_names_tex, 'g0');
M_.param_names_long = char(M_.param_names_long, 'g0');
M_.param_names = char(M_.param_names, 'x0');
M_.param_names_tex = char(M_.param_names_tex, 'x0');
M_.param_names_long = char(M_.param_names_long, 'x0');
M_.param_names = char(M_.param_names, 'px0');
M_.param_names_tex = char(M_.param_names_tex, 'px0');
M_.param_names_long = char(M_.param_names_long, 'px0');
M_.param_names = char(M_.param_names, 'pwx0');
M_.param_names_tex = char(M_.param_names_tex, 'pwx0');
M_.param_names_long = char(M_.param_names_long, 'pwx0');
M_.param_names = char(M_.param_names, 'omegae');
M_.param_names_tex = char(M_.param_names_tex, 'omegae');
M_.param_names_long = char(M_.param_names_long, 'omegae');
M_.param_names = char(M_.param_names, 'be');
M_.param_names_tex = char(M_.param_names_tex, 'be');
M_.param_names_long = char(M_.param_names_long, 'be');
M_.param_names = char(M_.param_names, 'sige');
M_.param_names_tex = char(M_.param_names_tex, 'sige');
M_.param_names_long = char(M_.param_names_long, 'sige');
M_.param_names = char(M_.param_names, 'omegad');
M_.param_names_tex = char(M_.param_names_tex, 'omegad');
M_.param_names_long = char(M_.param_names_long, 'omegad');
M_.param_names = char(M_.param_names, 'bd');
M_.param_names_tex = char(M_.param_names_tex, 'bd');
M_.param_names_long = char(M_.param_names_long, 'bd');
M_.param_names = char(M_.param_names, 'sigd');
M_.param_names_tex = char(M_.param_names_tex, 'sigd');
M_.param_names_long = char(M_.param_names_long, 'sigd');
M_.param_names = char(M_.param_names, 'xt0');
M_.param_names_tex = char(M_.param_names_tex, 'xt0');
M_.param_names_long = char(M_.param_names_long, 'xt0');
M_.param_names = char(M_.param_names, 'pw0');
M_.param_names_tex = char(M_.param_names_tex, 'pw0');
M_.param_names_long = char(M_.param_names_long, 'pw0');
M_.param_names = char(M_.param_names, 'pwm');
M_.param_names_tex = char(M_.param_names_tex, 'pwm');
M_.param_names_long = char(M_.param_names_long, 'pwm');
M_.param_names = char(M_.param_names, 'ma');
M_.param_names_tex = char(M_.param_names_tex, 'ma');
M_.param_names_long = char(M_.param_names_long, 'ma');
M_.param_names = char(M_.param_names, 'rho0');
M_.param_names_tex = char(M_.param_names_tex, 'rho0');
M_.param_names_long = char(M_.param_names_long, 'rho0');
M_.param_names = char(M_.param_names, 'rm');
M_.param_names_tex = char(M_.param_names_tex, 'rm');
M_.param_names_long = char(M_.param_names_long, 'rm');
M_.param_names = char(M_.param_names, 'a');
M_.param_names_tex = char(M_.param_names_tex, 'a');
M_.param_names_long = char(M_.param_names_long, 'a');
M_.param_names = char(M_.param_names, 'meta');
M_.param_names_tex = char(M_.param_names_tex, 'meta');
M_.param_names_long = char(M_.param_names_long, 'meta');
M_.param_names = char(M_.param_names, 'aran0');
M_.param_names_tex = char(M_.param_names_tex, 'aran0');
M_.param_names_long = char(M_.param_names_long, 'aran0');
M_.param_names = char(M_.param_names, 'tauhk');
M_.param_names_tex = char(M_.param_names_tex, 'tauhk');
M_.param_names_long = char(M_.param_names_long, 'tauhk');
M_.param_names = char(M_.param_names, 'taukk');
M_.param_names_tex = char(M_.param_names_tex, 'taukk');
M_.param_names_long = char(M_.param_names_long, 'taukk');
M_.param_names = char(M_.param_names, 'ivak');
M_.param_names_tex = char(M_.param_names_tex, 'ivak');
M_.param_names_long = char(M_.param_names_long, 'ivak');
M_.param_names = char(M_.param_names, 'arank');
M_.param_names_tex = char(M_.param_names_tex, 'arank');
M_.param_names_long = char(M_.param_names_long, 'arank');
M_.param_names = char(M_.param_names, 'psim0');
M_.param_names_tex = char(M_.param_names_tex, 'psim0');
M_.param_names_long = char(M_.param_names_long, 'psim0');
M_.param_names = char(M_.param_names, 'vr0');
M_.param_names_tex = char(M_.param_names_tex, 'vr0');
M_.param_names_long = char(M_.param_names_long, 'vr0');
M_.param_names = char(M_.param_names, 'ifdi0');
M_.param_names_tex = char(M_.param_names_tex, 'ifdi0');
M_.param_names_long = char(M_.param_names_long, 'ifdi0');
M_.param_names = char(M_.param_names, 'ir0');
M_.param_names_tex = char(M_.param_names_tex, 'ir0');
M_.param_names_long = char(M_.param_names_long, 'ir0');
M_.param_names = char(M_.param_names, 'gk');
M_.param_names_tex = char(M_.param_names_tex, 'gk');
M_.param_names_long = char(M_.param_names_long, 'gk');
M_.param_names = char(M_.param_names, 'ppet0');
M_.param_names_tex = char(M_.param_names_tex, 'ppet0');
M_.param_names_long = char(M_.param_names_long, 'ppet0');
M_.param_names = char(M_.param_names, 'qpet0');
M_.param_names_tex = char(M_.param_names_tex, 'qpet0');
M_.param_names_long = char(M_.param_names_long, 'qpet0');
M_.param_names = char(M_.param_names, 'share');
M_.param_names_tex = char(M_.param_names_tex, 'share');
M_.param_names_long = char(M_.param_names_long, 'share');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'rentas');
M_.param_names_tex = char(M_.param_names_tex, 'rentas');
M_.param_names_long = char(M_.param_names_long, 'rentas');
M_.param_names = char(M_.param_names, 'rcc');
M_.param_names_tex = char(M_.param_names_tex, 'rcc');
M_.param_names_long = char(M_.param_names_long, 'rcc');
M_.param_names = char(M_.param_names, 'oabc');
M_.param_names_tex = char(M_.param_names_tex, 'oabc');
M_.param_names_long = char(M_.param_names_long, 'oabc');
M_.param_names = char(M_.param_names, 'irb0');
M_.param_names_tex = char(M_.param_names_tex, 'irb0');
M_.param_names_long = char(M_.param_names_long, 'irb0');
M_.param_names = char(M_.param_names, 'rrb0');
M_.param_names_tex = char(M_.param_names_tex, 'rrb0');
M_.param_names_long = char(M_.param_names_long, 'rrb0');
M_.param_names = char(M_.param_names, 'alfaf');
M_.param_names_tex = char(M_.param_names_tex, 'alfaf');
M_.param_names_long = char(M_.param_names_long, 'alfaf');
M_.param_names = char(M_.param_names, 'kf');
M_.param_names_tex = char(M_.param_names_tex, 'kf');
M_.param_names_long = char(M_.param_names_long, 'kf');
M_.param_names = char(M_.param_names, 'alfah');
M_.param_names_tex = char(M_.param_names_tex, 'alfah');
M_.param_names_long = char(M_.param_names_long, 'alfah');
M_.param_names = char(M_.param_names, 'kh');
M_.param_names_tex = char(M_.param_names_tex, 'kh');
M_.param_names_long = char(M_.param_names_long, 'kh');
M_.param_names = char(M_.param_names, 'iri0');
M_.param_names_tex = char(M_.param_names_tex, 'iri0');
M_.param_names_long = char(M_.param_names_long, 'iri0');
M_.param_names = char(M_.param_names, 'sigmatc');
M_.param_names_tex = char(M_.param_names_tex, 'sigmatc');
M_.param_names_long = char(M_.param_names_long, 'sigmatc');
M_.param_names = char(M_.param_names, 'deltatc');
M_.param_names_tex = char(M_.param_names_tex, 'deltatc');
M_.param_names_long = char(M_.param_names_long, 'deltatc');
M_.param_names = char(M_.param_names, 'gamac');
M_.param_names_tex = char(M_.param_names_tex, 'gamac');
M_.param_names_long = char(M_.param_names_long, 'gamac');
M_.param_names = char(M_.param_names, 'gaman');
M_.param_names_tex = char(M_.param_names_tex, 'gaman');
M_.param_names_long = char(M_.param_names_long, 'gaman');
M_.param_names = char(M_.param_names, 'gamam');
M_.param_names_tex = char(M_.param_names_tex, 'gamam');
M_.param_names_long = char(M_.param_names_long, 'gamam');
M_.param_names = char(M_.param_names, 'gamav');
M_.param_names_tex = char(M_.param_names_tex, 'gamav');
M_.param_names_long = char(M_.param_names_long, 'gamav');
M_.param_names = char(M_.param_names, 'pib0');
M_.param_names_tex = char(M_.param_names_tex, 'pib0');
M_.param_names_long = char(M_.param_names_long, 'pib0');
M_.param_names = char(M_.param_names, 'pi0');
M_.param_names_tex = char(M_.param_names_tex, 'pi0');
M_.param_names_long = char(M_.param_names_long, 'pi0');
M_.param_names = char(M_.param_names, 'alfay');
M_.param_names_tex = char(M_.param_names_tex, 'alfay');
M_.param_names_long = char(M_.param_names_long, 'alfay');
M_.param_names = char(M_.param_names, 'alfapi');
M_.param_names_tex = char(M_.param_names_tex, 'alfapi');
M_.param_names_long = char(M_.param_names_long, 'alfapi');
M_.param_names = char(M_.param_names, 'kbb');
M_.param_names_tex = char(M_.param_names_tex, 'kbb');
M_.param_names_long = char(M_.param_names_long, 'kbb');
M_.param_names = char(M_.param_names, 'vbb');
M_.param_names_tex = char(M_.param_names_tex, 'vbb');
M_.param_names_long = char(M_.param_names_long, 'vbb');
M_.param_names = char(M_.param_names, 'rr');
M_.param_names_tex = char(M_.param_names_tex, 'rr');
M_.param_names_long = char(M_.param_names_long, 'rr');
M_.param_names = char(M_.param_names, 'spread');
M_.param_names_tex = char(M_.param_names_tex, 'spread');
M_.param_names_long = char(M_.param_names_long, 'spread');
M_.param_names = char(M_.param_names, 'spread2');
M_.param_names_tex = char(M_.param_names_tex, 'spread2');
M_.param_names_long = char(M_.param_names_long, 'spread2');
M_.param_names = char(M_.param_names, 'deltav');
M_.param_names_tex = char(M_.param_names_tex, 'deltav');
M_.param_names_long = char(M_.param_names_long, 'deltav');
M_.param_names = char(M_.param_names, 'kapa0');
M_.param_names_tex = char(M_.param_names_tex, 'kapa0');
M_.param_names_long = char(M_.param_names_long, 'kapa0');
M_.param_names = char(M_.param_names, 'tauv0');
M_.param_names_tex = char(M_.param_names_tex, 'tauv0');
M_.param_names_long = char(M_.param_names_long, 'tauv0');
M_.param_names = char(M_.param_names, 'psiv0');
M_.param_names_tex = char(M_.param_names_tex, 'psiv0');
M_.param_names_long = char(M_.param_names_long, 'psiv0');
M_.param_names = char(M_.param_names, 'bv');
M_.param_names_tex = char(M_.param_names_tex, 'bv');
M_.param_names_long = char(M_.param_names_long, 'bv');
M_.param_names = char(M_.param_names, 'sigv');
M_.param_names_tex = char(M_.param_names_tex, 'sigv');
M_.param_names_long = char(M_.param_names_long, 'sigv');
M_.param_names = char(M_.param_names, 'omegav');
M_.param_names_tex = char(M_.param_names_tex, 'omegav');
M_.param_names_long = char(M_.param_names_long, 'omegav');
M_.param_names = char(M_.param_names, 'taukv0');
M_.param_names_tex = char(M_.param_names_tex, 'taukv0');
M_.param_names_long = char(M_.param_names_long, 'taukv0');
M_.param_names = char(M_.param_names, 'sltv');
M_.param_names_tex = char(M_.param_names_tex, 'sltv');
M_.param_names_long = char(M_.param_names_long, 'sltv');
M_.param_names = char(M_.param_names, 'ppch');
M_.param_names_tex = char(M_.param_names_tex, 'ppch');
M_.param_names_long = char(M_.param_names_long, 'ppch');
M_.param_names = char(M_.param_names, 'ltv0');
M_.param_names_tex = char(M_.param_names_tex, 'ltv0');
M_.param_names_long = char(M_.param_names_long, 'ltv0');
M_.param_names = char(M_.param_names, 'chi0');
M_.param_names_tex = char(M_.param_names_tex, 'chi0');
M_.param_names_long = char(M_.param_names_long, 'chi0');
M_.param_names = char(M_.param_names, 'act');
M_.param_names_tex = char(M_.param_names_tex, 'act');
M_.param_names_long = char(M_.param_names_long, 'act');
M_.param_names = char(M_.param_names, 'mu');
M_.param_names_tex = char(M_.param_names_tex, 'mu');
M_.param_names_long = char(M_.param_names_long, 'mu');
M_.param_names = char(M_.param_names, 'sdomeg0');
M_.param_names_tex = char(M_.param_names_tex, 'sdomeg0');
M_.param_names_long = char(M_.param_names_long, 'sdomeg0');
M_.param_names = char(M_.param_names, 'rs0');
M_.param_names_tex = char(M_.param_names_tex, 'rs0');
M_.param_names_long = char(M_.param_names_long, 'rs0');
M_.param_names = char(M_.param_names, 'lamdi');
M_.param_names_tex = char(M_.param_names_tex, 'lamdi');
M_.param_names_long = char(M_.param_names_long, 'lamdi');
M_.param_names = char(M_.param_names, 'lamdv');
M_.param_names_tex = char(M_.param_names_tex, 'lamdv');
M_.param_names_long = char(M_.param_names_long, 'lamdv');
M_.param_names = char(M_.param_names, 'rho1');
M_.param_names_tex = char(M_.param_names_tex, 'rho1');
M_.param_names_long = char(M_.param_names_long, 'rho1');
M_.param_names = char(M_.param_names, 'rho2');
M_.param_names_tex = char(M_.param_names_tex, 'rho2');
M_.param_names_long = char(M_.param_names_long, 'rho2');
M_.param_names = char(M_.param_names, 'rho3');
M_.param_names_tex = char(M_.param_names_tex, 'rho3');
M_.param_names_long = char(M_.param_names_long, 'rho3');
M_.param_names = char(M_.param_names, 'rho4');
M_.param_names_tex = char(M_.param_names_tex, 'rho4');
M_.param_names_long = char(M_.param_names_long, 'rho4');
M_.param_names = char(M_.param_names, 'rho5');
M_.param_names_tex = char(M_.param_names_tex, 'rho5');
M_.param_names_long = char(M_.param_names_long, 'rho5');
M_.param_names = char(M_.param_names, 'rho6');
M_.param_names_tex = char(M_.param_names_tex, 'rho6');
M_.param_names_long = char(M_.param_names_long, 'rho6');
M_.param_names = char(M_.param_names, 'rho7');
M_.param_names_tex = char(M_.param_names_tex, 'rho7');
M_.param_names_long = char(M_.param_names_long, 'rho7');
M_.param_names = char(M_.param_names, 'rho8');
M_.param_names_tex = char(M_.param_names_tex, 'rho8');
M_.param_names_long = char(M_.param_names_long, 'rho8');
M_.param_names = char(M_.param_names, 'rho9');
M_.param_names_tex = char(M_.param_names_tex, 'rho9');
M_.param_names_long = char(M_.param_names_long, 'rho9');
M_.param_names = char(M_.param_names, 'rho10');
M_.param_names_tex = char(M_.param_names_tex, 'rho10');
M_.param_names_long = char(M_.param_names_long, 'rho10');
M_.param_names = char(M_.param_names, 'rho11');
M_.param_names_tex = char(M_.param_names_tex, 'rho11');
M_.param_names_long = char(M_.param_names_long, 'rho11');
M_.param_names = char(M_.param_names, 'rho12');
M_.param_names_tex = char(M_.param_names_tex, 'rho12');
M_.param_names_long = char(M_.param_names_long, 'rho12');
M_.param_names = char(M_.param_names, 'rho13');
M_.param_names_tex = char(M_.param_names_tex, 'rho13');
M_.param_names_long = char(M_.param_names_long, 'rho13');
M_.param_names = char(M_.param_names, 'rho14');
M_.param_names_tex = char(M_.param_names_tex, 'rho14');
M_.param_names_long = char(M_.param_names_long, 'rho14');
M_.param_names = char(M_.param_names, 'rho15');
M_.param_names_tex = char(M_.param_names_tex, 'rho15');
M_.param_names_long = char(M_.param_names_long, 'rho15');
M_.param_names = char(M_.param_names, 'rho16');
M_.param_names_tex = char(M_.param_names_tex, 'rho16');
M_.param_names_long = char(M_.param_names_long, 'rho16');
M_.param_names = char(M_.param_names, 'rho17');
M_.param_names_tex = char(M_.param_names_tex, 'rho17');
M_.param_names_long = char(M_.param_names_long, 'rho17');
M_.param_names = char(M_.param_names, 'rho18');
M_.param_names_tex = char(M_.param_names_tex, 'rho18');
M_.param_names_long = char(M_.param_names_long, 'rho18');
M_.param_names = char(M_.param_names, 'rho19');
M_.param_names_tex = char(M_.param_names_tex, 'rho19');
M_.param_names_long = char(M_.param_names_long, 'rho19');
M_.param_names = char(M_.param_names, 'rho20');
M_.param_names_tex = char(M_.param_names_tex, 'rho20');
M_.param_names_long = char(M_.param_names_long, 'rho20');
M_.param_names = char(M_.param_names, 'rho21');
M_.param_names_tex = char(M_.param_names_tex, 'rho21');
M_.param_names_long = char(M_.param_names_long, 'rho21');
M_.param_names = char(M_.param_names, 'rho22');
M_.param_names_tex = char(M_.param_names_tex, 'rho22');
M_.param_names_long = char(M_.param_names_long, 'rho22');
M_.param_names = char(M_.param_names, 'rho23');
M_.param_names_tex = char(M_.param_names_tex, 'rho23');
M_.param_names_long = char(M_.param_names_long, 'rho23');
M_.param_names = char(M_.param_names, 'rho24');
M_.param_names_tex = char(M_.param_names_tex, 'rho24');
M_.param_names_long = char(M_.param_names_long, 'rho24');
M_.param_names = char(M_.param_names, 'rho25');
M_.param_names_tex = char(M_.param_names_tex, 'rho25');
M_.param_names_long = char(M_.param_names_long, 'rho25');
M_.param_names = char(M_.param_names, 'rho26');
M_.param_names_tex = char(M_.param_names_tex, 'rho26');
M_.param_names_long = char(M_.param_names_long, 'rho26');
M_.param_names = char(M_.param_names, 'cor1');
M_.param_names_tex = char(M_.param_names_tex, 'cor1');
M_.param_names_long = char(M_.param_names_long, 'cor1');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 26;
M_.endo_nbr = 82;
M_.param_nbr = 119;
M_.orig_endo_nbr = 82;
M_.aux_vars = [];
M_.Sigma_e = zeros(26, 26);
M_.Correlation_matrix = eye(26, 26);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('Modelo_static');
erase_compiled_function('Modelo_dynamic');
M_.orig_eq_nbr = 82;
M_.eq_nbr = 82;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 0 42 124;
 0 43 0;
 0 44 0;
 0 45 125;
 1 46 0;
 2 47 0;
 0 48 0;
 0 49 0;
 3 50 0;
 4 51 0;
 5 52 0;
 6 53 0;
 0 54 0;
 0 55 0;
 0 56 126;
 7 57 0;
 8 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 9 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 10 69 0;
 0 70 0;
 11 71 0;
 0 72 0;
 12 73 0;
 13 74 0;
 14 75 0;
 15 76 0;
 16 77 0;
 17 78 0;
 18 79 0;
 19 80 0;
 0 81 127;
 20 82 0;
 21 83 0;
 22 84 0;
 0 85 0;
 0 86 0;
 0 87 0;
 0 88 128;
 0 89 129;
 23 90 130;
 0 91 0;
 24 92 0;
 25 93 131;
 26 94 0;
 27 95 0;
 0 96 0;
 0 97 0;
 0 98 0;
 0 99 0;
 28 100 0;
 0 101 0;
 0 102 132;
 0 103 133;
 0 104 0;
 0 105 0;
 0 106 0;
 29 107 134;
 30 108 135;
 31 109 136;
 32 110 0;
 33 111 0;
 34 112 137;
 35 113 0;
 36 114 0;
 37 115 0;
 38 116 0;
 0 117 138;
 0 118 0;
 0 119 0;
 39 120 0;
 40 121 0;
 41 122 0;
 0 123 0;]';
M_.nstatic = 32;
M_.nfwrd   = 9;
M_.npred   = 35;
M_.nboth   = 6;
M_.nsfwrd   = 15;
M_.nspred   = 41;
M_.ndynamic   = 50;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:26];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(82, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(26, 1);
M_.params = NaN(119, 1);
M_.NNZDerivatives = [462; -1; -1];
close all;
M_.params( 1 ) = 0.8421561253626927;
psin0 = M_.params( 1 );
M_.params( 2 ) = 0.9726969859330633;
beta = M_.params( 2 );
M_.params( 3 ) = 1.011289;
theta = M_.params( 3 );
M_.params( 4 ) = 0.13921;
tauh0 = M_.params( 4 );
M_.params( 5 ) = 0.942928263;
delta = M_.params( 5 );
M_.params( 6 ) = 1.561073496;
gama = M_.params( 6 );
M_.params( 7 ) = 0.133974;
tauk0 = M_.params( 7 );
M_.params( 8 ) = 0.760360883;
f0 = M_.params( 8 );
M_.params( 9 ) = 0.80712262;
fk0 = M_.params( 9 );
M_.params( 10 ) = 0.276098782;
alfa1 = M_.params( 10 );
M_.params( 11 ) = 0.023635479;
alfa2 = M_.params( 11 );
M_.params( 12 ) = 0.030266205;
alfa3 = M_.params( 12 );
M_.params( 13 ) = 26.59720303;
z0 = M_.params( 13 );
M_.params( 14 ) = 2.064665685;
b = M_.params( 14 );
M_.params( 15 ) = 1.5;
sig = M_.params( 15 );
M_.params( 16 ) = 0.330468306;
omega = M_.params( 16 );
M_.params( 17 ) = 0.123953184;
iva0 = M_.params( 17 );
M_.params( 18 ) = 3.946133413;
g0 = M_.params( 18 );
M_.params( 19 ) = 1.88796393;
x0 = M_.params( 19 );
M_.params( 20 ) = 1;
px0 = M_.params( 20 );
M_.params( 21 ) = 1;
pwx0 = M_.params( 21 );
M_.params( 22 ) = 0.226246806;
omegae = M_.params( 22 );
M_.params( 23 ) = 1.451223777;
be = M_.params( 23 );
M_.params( 24 ) = 3;
sige = M_.params( 24 );
M_.params( 25 ) = 0.712316809;
omegad = M_.params( 25 );
M_.params( 26 ) = 2.413222496;
bd = M_.params( 26 );
M_.params( 27 ) = (-2);
sigd = M_.params( 27 );
M_.params( 28 ) = 77.40652112;
xt0 = M_.params( 28 );
M_.params( 29 ) = 1;
pw0 = M_.params( 29 );
M_.params( 30 ) = 0.972498643;
pwm = M_.params( 30 );
M_.params( 31 ) = 0.052631579;
ma = M_.params( 31 );
M_.params( 32 ) = 0.5;
rho0 = M_.params( 32 );
M_.params( 33 ) = 0.021307;
rm = M_.params( 33 );
M_.params( 34 ) = 0.061189212;
a = M_.params( 34 );
M_.params( 35 ) = 0.408404801;
meta = M_.params( 35 );
M_.params( 36 ) = 0.02827907;
aran0 = M_.params( 36 );
M_.params( 37 ) = 1;
tauhk = M_.params( 37 );
M_.params( 38 ) = 2;
taukk = M_.params( 38 );
M_.params( 39 ) = 2;
ivak = M_.params( 39 );
M_.params( 40 ) = 2;
arank = M_.params( 40 );
M_.params( 41 ) = 0.07377068;
psim0 = M_.params( 41 );
M_.params( 42 ) = 0.036093325;
vr0 = M_.params( 42 );
M_.params( 43 ) = 0.247142369;
ifdi0 = M_.params( 43 );
M_.params( 44 ) = 1.06552350;
ir0 = M_.params( 44 );
M_.params( 45 ) = 2;
gk = M_.params( 45 );
M_.params( 46 ) = 1;
ppet0 = M_.params( 46 );
M_.params( 47 ) = 0.801901957;
qpet0 = M_.params( 47 );
M_.params( 48 ) = 0.292740852;
share = M_.params( 48 );
M_.params( 49 ) = 20;
epsilon = M_.params( 49 );
M_.params( 50 ) = 1.832450981;
rentas = M_.params( 50 );
M_.params( 51 ) = 0.476790463;
rcc = M_.params( 51 );
M_.params( 52 ) = 0.037022972;
oabc = M_.params( 52 );
M_.params( 53 ) = 1.0570588;
irb0 = M_.params( 53 );
M_.params( 54 ) = 0.076836026;
rrb0 = M_.params( 54 );
M_.params( 55 ) = 1.2;
alfaf = M_.params( 55 );
M_.params( 56 ) = 0.017660472;
kf = M_.params( 56 );
M_.params( 57 ) = 1.2;
alfah = M_.params( 57 );
M_.params( 58 ) = 0.040510778;
kh = M_.params( 58 );
M_.params( 59 ) = 1.10215157;
iri0 = M_.params( 59 );
M_.params( 60 ) = 10.00000000;
sigmatc = M_.params( 60 );
M_.params( 61 ) = 1.44595993;
deltatc = M_.params( 61 );
M_.params( 62 ) = 0.57000000;
gamac = M_.params( 62 );
M_.params( 63 ) = 2.50000000;
gaman = M_.params( 63 );
M_.params( 64 ) = 2.00000000;
gamam = M_.params( 64 );
M_.params( 65 ) = 5.00000000;
gamav = M_.params( 65 );
M_.params( 66 ) = 17.18740916;
pib0 = M_.params( 66 );
M_.params( 67 ) = 1.0300000;
pi0 = M_.params( 67 );
M_.params( 68 ) = 0.5000000;
alfay = M_.params( 68 );
M_.params( 69 ) = 1.5000000;
alfapi = M_.params( 69 );
M_.params( 70 ) = (-0.08470711);
kbb = M_.params( 70 );
M_.params( 71 ) = (-0.272727273);
vbb = M_.params( 71 );
M_.params( 72 ) = 0.0270588;
rr = M_.params( 72 );
M_.params( 73 ) = 0.036851467;
spread = M_.params( 73 );
M_.params( 74 ) = 0.008464672;
spread2 = M_.params( 74 );
M_.params( 75 ) = 0.909317602;
deltav = M_.params( 75 );
M_.params( 76 ) = 1;
kapa0 = M_.params( 76 );
M_.params( 77 ) = 1.0000000;
tauv0 = M_.params( 77 );
M_.params( 78 ) = 404.907184;
psiv0 = M_.params( 78 );
M_.params( 79 ) = 2.950827;
bv = M_.params( 79 );
M_.params( 80 ) = (-2);
sigv = M_.params( 80 );
M_.params( 81 ) = 0.796372447;
omegav = M_.params( 81 );
M_.params( 82 ) = 1;
taukv0 = M_.params( 82 );
M_.params( 83 ) = 0.500000000;
sltv = M_.params( 83 );
M_.params( 84 ) = 0.403621206;
ppch = M_.params( 84 );
M_.params( 85 ) = 0.700000000;
ltv0 = M_.params( 85 );
M_.params( 86 ) = 0.001725;
chi0 = M_.params( 86 );
M_.params( 87 ) = 0.957405739;
act = M_.params( 87 );
M_.params( 88 ) = 0;
mu = M_.params( 88 );
M_.params( 89 ) = 0.5;
sdomeg0 = M_.params( 89 );
M_.params( 90 ) = 0.115;
rs0 = M_.params( 90 );
M_.params( 91 ) = 0.5;
lamdi = M_.params( 91 );
M_.params( 92 ) = 0.75;
lamdv = M_.params( 92 );
M_.params( 1 ) = 0.8421561253626927;
psin0 = M_.params( 1 );
M_.params( 2 ) = 0.9726969859330633;
beta = M_.params( 2 );
M_.params( 3 ) = 1.011289;
theta = M_.params( 3 );
M_.params( 4 ) = 0.13921;
tauh0 = M_.params( 4 );
M_.params( 5 ) = 0.942928263;
delta = M_.params( 5 );
M_.params( 6 ) = 1.561073496;
gama = M_.params( 6 );
M_.params( 7 ) = 0.133974;
tauk0 = M_.params( 7 );
M_.params( 8 ) = 0.760360883;
f0 = M_.params( 8 );
M_.params( 9 ) = 0.80712262;
fk0 = M_.params( 9 );
M_.params( 10 ) = 0.276098782;
alfa1 = M_.params( 10 );
M_.params( 11 ) = 0.023635479;
alfa2 = M_.params( 11 );
M_.params( 12 ) = 0.030266205;
alfa3 = M_.params( 12 );
M_.params( 13 ) = 26.59720303;
z0 = M_.params( 13 );
M_.params( 14 ) = 2.064665685;
b = M_.params( 14 );
M_.params( 15 ) = 1.5;
sig = M_.params( 15 );
M_.params( 16 ) = 0.330468306;
omega = M_.params( 16 );
M_.params( 17 ) = 0.123953184;
iva0 = M_.params( 17 );
M_.params( 18 ) = 3.946133413;
g0 = M_.params( 18 );
M_.params( 19 ) = 1.88796393;
x0 = M_.params( 19 );
M_.params( 20 ) = 1;
px0 = M_.params( 20 );
M_.params( 21 ) = 1;
pwx0 = M_.params( 21 );
M_.params( 22 ) = 0.226246806;
omegae = M_.params( 22 );
M_.params( 23 ) = 1.451223777;
be = M_.params( 23 );
M_.params( 24 ) = 3;
sige = M_.params( 24 );
M_.params( 25 ) = 0.712316809;
omegad = M_.params( 25 );
M_.params( 26 ) = 2.413222496;
bd = M_.params( 26 );
M_.params( 27 ) = (-2);
sigd = M_.params( 27 );
M_.params( 28 ) = 77.40652112;
xt0 = M_.params( 28 );
M_.params( 29 ) = 1;
pw0 = M_.params( 29 );
M_.params( 30 ) = 0.972498643;
pwm = M_.params( 30 );
M_.params( 31 ) = 0.052631579;
ma = M_.params( 31 );
M_.params( 32 ) = 0.5;
rho0 = M_.params( 32 );
M_.params( 33 ) = 0.021307;
rm = M_.params( 33 );
M_.params( 34 ) = 0.061189212;
a = M_.params( 34 );
M_.params( 35 ) = 0.408404801;
meta = M_.params( 35 );
M_.params( 36 ) = 0.02827907;
aran0 = M_.params( 36 );
M_.params( 37 ) = 1;
tauhk = M_.params( 37 );
M_.params( 38 ) = 2;
taukk = M_.params( 38 );
M_.params( 39 ) = 2;
ivak = M_.params( 39 );
M_.params( 40 ) = 2;
arank = M_.params( 40 );
M_.params( 41 ) = 0.07377068;
psim0 = M_.params( 41 );
M_.params( 42 ) = 0.036093325;
vr0 = M_.params( 42 );
M_.params( 43 ) = 0.247142369;
ifdi0 = M_.params( 43 );
M_.params( 44 ) = 1.06552350;
ir0 = M_.params( 44 );
M_.params( 45 ) = 2;
gk = M_.params( 45 );
M_.params( 46 ) = 1;
ppet0 = M_.params( 46 );
M_.params( 47 ) = 0.801901957;
qpet0 = M_.params( 47 );
M_.params( 48 ) = 0.292740852;
share = M_.params( 48 );
M_.params( 49 ) = 20;
epsilon = M_.params( 49 );
M_.params( 50 ) = 1.832450981;
rentas = M_.params( 50 );
M_.params( 51 ) = 0.476790463;
rcc = M_.params( 51 );
M_.params( 52 ) = 0.037022972;
oabc = M_.params( 52 );
M_.params( 53 ) = 1.0570588;
irb0 = M_.params( 53 );
M_.params( 54 ) = 0.076836026;
rrb0 = M_.params( 54 );
M_.params( 55 ) = 1.2;
alfaf = M_.params( 55 );
M_.params( 56 ) = 0.017660472;
kf = M_.params( 56 );
M_.params( 57 ) = 1.2;
alfah = M_.params( 57 );
M_.params( 58 ) = 0.040510778;
kh = M_.params( 58 );
M_.params( 59 ) = 1.10215157;
iri0 = M_.params( 59 );
M_.params( 60 ) = 10.00000000;
sigmatc = M_.params( 60 );
M_.params( 61 ) = 1.44595993;
deltatc = M_.params( 61 );
M_.params( 62 ) = 0.57000000;
gamac = M_.params( 62 );
M_.params( 63 ) = 2.50000000;
gaman = M_.params( 63 );
M_.params( 64 ) = 2.00000000;
gamam = M_.params( 64 );
M_.params( 65 ) = 5.00000000;
gamav = M_.params( 65 );
M_.params( 66 ) = 17.18740916;
pib0 = M_.params( 66 );
M_.params( 67 ) = 1.0300000;
pi0 = M_.params( 67 );
M_.params( 68 ) = 0.5000000;
alfay = M_.params( 68 );
M_.params( 69 ) = 1.5000000;
alfapi = M_.params( 69 );
M_.params( 70 ) = (-0.08470711);
kbb = M_.params( 70 );
M_.params( 71 ) = (-0.272727273);
vbb = M_.params( 71 );
M_.params( 72 ) = 0.0270588;
rr = M_.params( 72 );
M_.params( 73 ) = 0.036851467;
spread = M_.params( 73 );
M_.params( 74 ) = 0.008464672;
spread2 = M_.params( 74 );
M_.params( 75 ) = 0.909317602;
deltav = M_.params( 75 );
M_.params( 76 ) = 1;
kapa0 = M_.params( 76 );
M_.params( 77 ) = 1.0000000;
tauv0 = M_.params( 77 );
M_.params( 78 ) = 404.907184;
psiv0 = M_.params( 78 );
M_.params( 79 ) = 2.950827;
bv = M_.params( 79 );
M_.params( 80 ) = (-2);
sigv = M_.params( 80 );
M_.params( 81 ) = 0.796372447;
omegav = M_.params( 81 );
M_.params( 82 ) = 1;
taukv0 = M_.params( 82 );
M_.params( 83 ) = 0.500000000;
sltv = M_.params( 83 );
M_.params( 84 ) = 0.403621206;
ppch = M_.params( 84 );
M_.params( 85 ) = 0.700000000;
ltv0 = M_.params( 85 );
M_.params( 86 ) = 0.001725;
chi0 = M_.params( 86 );
M_.params( 87 ) = 0.957405739;
act = M_.params( 87 );
M_.params( 88 ) = 0;
mu = M_.params( 88 );
M_.params( 89 ) = 0.5;
sdomeg0 = M_.params( 89 );
M_.params( 90 ) = 0.115;
rs0 = M_.params( 90 );
M_.params( 91 ) = 0.5;
lamdi = M_.params( 91 );
M_.params( 92 ) = 0.75;
lamdv = M_.params( 92 );
M_.params( 93 ) = 0.95;
rho1 = M_.params( 93 );
M_.params( 94 ) = 0.95;
rho2 = M_.params( 94 );
M_.params( 95 ) = 0.95;
rho3 = M_.params( 95 );
M_.params( 96 ) = 0.95;
rho4 = M_.params( 96 );
M_.params( 97 ) = 0.95;
rho5 = M_.params( 97 );
M_.params( 98 ) = 0.95;
rho6 = M_.params( 98 );
M_.params( 99 ) = 0.95;
rho7 = M_.params( 99 );
M_.params( 100 ) = 0.95;
rho8 = M_.params( 100 );
M_.params( 101 ) = 0.95;
rho9 = M_.params( 101 );
M_.params( 102 ) = 0.95;
rho10 = M_.params( 102 );
M_.params( 103 ) = 0.95;
rho11 = M_.params( 103 );
M_.params( 104 ) = 0.95;
rho12 = M_.params( 104 );
M_.params( 105 ) = 0.95;
rho13 = M_.params( 105 );
M_.params( 106 ) = 0.95;
rho14 = M_.params( 106 );
M_.params( 107 ) = 0.95;
rho15 = M_.params( 107 );
M_.params( 108 ) = 0.95;
rho16 = M_.params( 108 );
M_.params( 109 ) = 0.95;
rho17 = M_.params( 109 );
M_.params( 110 ) = 0.95;
rho18 = M_.params( 110 );
M_.params( 111 ) = 0.95;
rho19 = M_.params( 111 );
M_.params( 112 ) = 0.95;
rho20 = M_.params( 112 );
M_.params( 113 ) = 0.95;
rho21 = M_.params( 113 );
M_.params( 114 ) = 0.95;
rho22 = M_.params( 114 );
M_.params( 115 ) = 0.95;
rho23 = M_.params( 115 );
M_.params( 116 ) = 0.95;
rho24 = M_.params( 116 );
M_.params( 117 ) = 0.95;
rho25 = M_.params( 117 );
M_.params( 118 ) = 0.95;
rho26 = M_.params( 118 );
M_.params( 119 ) = 0.95;
cor1 = M_.params( 119 );
sigma=0.01;
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 1 ) = 2.459706244;
oo_.steady_state( 2 ) = (-0.754458899);
oo_.steady_state( 3 ) = 2.96594119;
oo_.steady_state( 4 ) = 0.063466224;
oo_.steady_state( 5 ) = 1.897751157;
oo_.steady_state( 6 ) = 0;
oo_.steady_state( 7 ) = (-2.694181374);
oo_.steady_state( 8 ) = 0.486164058;
oo_.steady_state( 9 ) = (-1.397790717);
oo_.steady_state( 10 ) = 3.180345432;
oo_.steady_state( 11 ) = 1.296390656;
oo_.steady_state( 12 ) = 2.166662188;
oo_.steady_state( 13 ) = (-1.84415562);
oo_.steady_state( 14 ) = (-2.418210605);
oo_.steady_state( 15 ) = 0.16802575;
oo_.steady_state( 16 ) = 1.842207949;
oo_.steady_state( 17 ) = 0;
oo_.steady_state( 18 ) = 2.663253848;
oo_.steady_state( 19 ) = 1.372736217;
oo_.steady_state( 20 ) = 2.448824812;
oo_.steady_state( 21 ) = 1.389723192;
oo_.steady_state( 22 ) = 1.948680653;
oo_.steady_state( 23 ) = 0.635498962;
oo_.steady_state( 24 ) = 0;
oo_.steady_state( 25 ) = 0;
oo_.steady_state( 26 ) = 0;
oo_.steady_state( 27 ) = 4.324378417;
oo_.steady_state( 28 ) = 4.349071029;
oo_.steady_state( 29 ) = 0;
oo_.steady_state( 30 ) = 2.84417709;
oo_.steady_state( 31 ) = (-3.072678803);
oo_.steady_state( 32 ) = (-1.971772928);
oo_.steady_state( 33 ) = (-2.010112603);
oo_.steady_state( 34 ) = (-0.273962113);
oo_.steady_state( 35 ) = (-0.214279677);
oo_.steady_state( 36 ) = 3.280806061;
oo_.steady_state( 37 ) = (-2.087851335);
oo_.steady_state( 38 ) = (-3.565633332);
oo_.steady_state( 39 ) = 0.792025694;
oo_.steady_state( 40 ) = 0.029558802;
oo_.steady_state( 41 ) = 0.036093325;
oo_.steady_state( 42 ) = 0;
oo_.steady_state( 43 ) = (-0.220768927);
oo_.steady_state( 44 ) = (-0.051293294);
oo_.steady_state( 45 ) = (-0.332478425);
oo_.steady_state( 46 ) = 0;
oo_.steady_state( 47 ) = 3.272312421;
oo_.steady_state( 48 ) = 3.323605715;
oo_.steady_state( 49 ) = 0.097264242;
oo_.steady_state( 50 ) = (-0.974937334);
oo_.steady_state( 51 ) = (-0.49866339);
oo_.steady_state( 52 ) = 0.055490357;
oo_.steady_state( 53 ) = 1.92449695;
oo_.steady_state( 54 ) = (-1.710224263);
oo_.steady_state( 55 ) = 0.063256546;
oo_.steady_state( 56 ) = 0;
oo_.steady_state( 57 ) = (-0.117259771);
oo_.steady_state( 58 ) = 0.119359758;
oo_.steady_state( 59 ) = 0;
oo_.steady_state( 60 ) = (-0.127625826);
oo_.steady_state( 61 ) = (-3.041199347);
oo_.steady_state( 62 ) = 0;
oo_.steady_state( 63 ) = (-0.127625826);
oo_.steady_state( 64 ) = 2.59992291;
oo_.steady_state( 65 ) = 0;
oo_.steady_state( 66 ) = 0;
oo_.steady_state( 67 ) = 0;
oo_.steady_state( 68 ) = (-0.356674944);
oo_.steady_state( 69 ) = 0.113328685;
oo_.steady_state( 70 ) = (-0.013498939);
oo_.steady_state( 71 ) = 0;
oo_.steady_state( 72 ) = (-2.566081655);
oo_.steady_state( 73 ) = 6.003657866;
oo_.steady_state( 74 ) = (-2.606793879);
oo_.steady_state( 75 ) = (-0.174441902);
oo_.steady_state( 76 ) = 5.444972737;
oo_.steady_state( 77 ) = (-2.301550103);
oo_.steady_state( 78 ) = (-0.049735903);
oo_.steady_state( 79 ) = (-2.162823151);
oo_.steady_state( 80 ) = (-3.248639373);
oo_.steady_state( 81 ) = (-6.362528228);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(18, 18) = sigma^2;
resid(1);
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.order = 1;
options_.periods = 2100;
var_list_ = char();
info = stoch_simul(var_list_);
var_list_ = char('pib','y');
dynasave('RESULT',var_list_);
save('Modelo_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('Modelo_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('Modelo_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('Modelo_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('Modelo_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('Modelo_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('Modelo_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
